### ISSUE TITLE
ansible task blocking when installing zfs

### ISSUE THREAD

**Issue by purema4** [purema4/zfs-vagrant#1]
Je crois sincèrement que le script block, car quand on install zfs-dkms normalement, il y a un dialog qui demande d'appuyer sur [Enter]

J'essaye de trouver une solution à ça...

j'ai déjà essayé ```yes '' | apt install -y --force-yes -t jessie-backports zfs-dmks``` mais rien de concluant...

**Comment by mikefaille** [comment]
--> https://docs.ansible.com/ansible/expect_module.html

**Comment by purema4** [comment]
@mikefaille fixé le bug!!!
C'était bizzare avec expect de ansible, car il fallait des packages de python qui sont dans le repo "test" de debian, et je devais aussi mettre à jour ma version de ansible, en l'occurence la version de tout le monde.

Alors j'ai juste ajouté ``` DEBIAN_FRONTEND=noninteractive apt install --force-yes -y -t jessie-backports zfs-dkms ``` ce qui permet de "skipper" le dialog.. 

Voilà..

**Comment by purema4** [comment]
Dernière update, le script ansible bloque encore lorsque le prompt ouvre. Je crois qu'avec le module expect, je ne suis pas nécéssairement capable de chercher le bon regex pour le prompt.

**Comment by mikefaille** [comment]
Fixé par : https://github.com/purema4/zfs-vagrant/pull/4
