### ISSUE TITLE
bridge impossible avec un iface wifi

### ISSUE THREAD

**Issue by mikefaille** [purema4/zfs-vagrant#3]
Le bridge cause un problème avec un interface wifi sous Linux.

Il faut savoir qu'une interface wifi utilise une couche réseau bas niveau permettant l'enregistrement sur un point d'accès wifi; alors que sous Linux, le bidge a besoin d'un interface pouvant utiliser directement la couche 2.

Le résultat, le bridge est non fonctionnelle avec un interface wifi. Pour corriger ça, supprimer la ligne du réseau publique.

**Comment by mikefaille** [comment]
Fixé par : https://github.com/purema4/zfs-vagrant/pull/4

**Comment by purema4** [comment]
Removed ```config.vm.network "public_network"``` from Vagrant file.
C'est bon à savoir pour linux. Desfois on pense "windows" et ce n'est pas toujours la meilleur façon.
Merci!
