### ISSUE TITLE
Bloque à la tâche  ZFS | Set Dedup

### ISSUE THREAD

**Issue by mikefaille** [purema4/zfs-vagrant#6]
Voici les logs : 

TASK [pool-creation : ZFS | Set Dedup] *****************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: state,name"}

**Comment by purema4** [comment]
ça devrait être good 
https://github.com/purema4/zfs-vagrant/commit/2afe05168b7e6711fa744c0e255069fff92fc25c
