### ISSUE TITLE
Augmentation de la visibilité l'avancement

### ISSUE THREAD

**Issue by mikefaille** [purema4/zfs-vagrant#9]
Pourrais-tu faire un transfert de ownership du repos à clubcedille afin que les membres puissent suivre l'avancement des travaux ? 
Cheers

**Comment by purema4** [comment]
Je te l'ai envoyé à toi, tu devrais recevoir une demande

**Comment by purema4** [comment]
Oh je viens de voir que tu l'as mtn XD

**Comment by purema4** [comment]
transfer done? perf :)
